"use client"
import React, { useRef } from 'react'
import { Button } from '@/components/ui/button'
import { Card, CardContent, CardHeader, CardTitle } from '@/components/ui/card'
import { cn } from '@/lib/utils'
import { Download, FileText, User, Calendar, Stethoscope, Pill, ClipboardList } from 'lucide-react'
import jsPDF from 'jspdf'
import html2canvas from 'html2canvas'

interface MedicalReportProps {
  report: {
    patientInfo: {
      name: string
      age: string
    }
    chiefComplaint: string
    medicalHistory: string
    assessment: string
    prescription: string
    followUp: string
    generatedAt: string
  } | null
  sessionId?: string
  hasServerPdf?: boolean
  onDownload?: () => void
}

function MedicalReport({ report, sessionId, hasServerPdf = false, onDownload }: MedicalReportProps) {
  const reportRef = useRef<HTMLDivElement>(null)

  if (!report) {
    return (
      <Card className="w-full max-w-4xl mx-auto mt-6">
        <CardContent className="p-6">
          <div className="text-center text-gray-500">
            <FileText className="w-12 h-12 mx-auto mb-4 opacity-50" />
            <p>No medical report available yet.</p>
            <p className="text-sm">Complete a consultation to generate a report.</p>
          </div>
        </CardContent>
      </Card>
    )
  }

  const formatDate = (dateString: string) => {
    return new Date(dateString).toLocaleDateString('en-US', {
      year: 'numeric',
      month: 'long',
      day: 'numeric',
      hour: '2-digit',
      minute: '2-digit'
    })
  }

  const generatePDFContent = () => {
    const content = `
MEDICAL CONSULTATION REPORT
Generated on: ${formatDate(report.generatedAt)}

PATIENT INFORMATION
Name: ${report.patientInfo.name}
Age: ${report.patientInfo.age}

CHIEF COMPLAINT
${report.chiefComplaint}

MEDICAL HISTORY
${report.medicalHistory}

ASSESSMENT/DIAGNOSIS
${report.assessment}

PRESCRIPTION/RECOMMENDATIONS
${report.prescription}

FOLLOW-UP INSTRUCTIONS
${report.followUp}

---
This report was generated by AI Medical Assistant
Please consult with a healthcare professional for final diagnosis and treatment.
    `.trim()

    return content
  }

  const handleDownload = async () => {
    if (!reportRef.current) return

    // Prefer server PDF if available
    if (hasServerPdf && sessionId) {
      try {
        const downloadUrl = `/api/session-chat/download?sessionId=${encodeURIComponent(sessionId)}`
        const res = await fetch(downloadUrl)
        if (!res.ok) throw new Error('Server PDF download failed')

        const blob = await res.blob()

        // extract filename from content-disposition header if present
        const disp = res.headers.get('Content-Disposition') || ''
        let filename = `medical-report-${sessionId}.pdf`
        const match = disp.match(/filename="?(.*?)"?(;|$)/i)
        if (match && match[1]) filename = match[1]

        const url = URL.createObjectURL(blob)
        const a = document.createElement('a')
        a.href = url
        a.download = filename
        document.body.appendChild(a)
        a.click()
        a.remove()
        URL.revokeObjectURL(url)

        if (onDownload) onDownload()
        return
      } catch (err) {
        console.warn('Server PDF download failed — falling back to client-side generation', err)
        // continue to client-side generation
      }
    }

    // Client-side PDF generation fallback
    try {
      const canvas = await html2canvas(reportRef.current, {
        scale: 2,
        useCORS: true,
        allowTaint: true,
        backgroundColor: '#ffffff'
      })

      const imgData = canvas.toDataURL('image/png')
      const pdf = new jsPDF('p', 'mm', 'a4')

      // Calculate dimensions to fit the content
      const imgWidth = 210 // A4 width in mm
      const pageHeight = 295 // A4 height in mm
      const imgHeight = (canvas.height * imgWidth) / canvas.width
      let heightLeft = imgHeight

      let position = 0

      // Add first page
      pdf.addImage(imgData, 'PNG', 0, position, imgWidth, imgHeight)
      heightLeft -= pageHeight

      // Add additional pages if content is longer than one page
      while (heightLeft >= 0) {
        position = heightLeft - imgHeight
        pdf.addPage()
        pdf.addImage(imgData, 'PNG', 0, position, imgWidth, imgHeight)
        heightLeft -= pageHeight
      }

      // Download the PDF
      const fileName = `medical-report-${report.patientInfo.name.replace(/\s+/g, '-')}-${new Date().toISOString().split('T')[0]}.pdf`
      pdf.save(fileName)

      if (onDownload) onDownload()
    } catch (error) {
      console.error('Error generating PDF (client-side):', error)
      // Fallback to text download if PDF generation fails
      const content = generatePDFContent()
      const blob = new Blob([content], { type: 'text/plain' })
      const url = URL.createObjectURL(blob)
      const a = document.createElement('a')
      a.href = url
      a.download = `medical-report-${report.patientInfo.name.replace(/\s+/g, '-')}-${new Date().toISOString().split('T')[0]}.txt`
      document.body.appendChild(a)
      a.click()
      document.body.removeChild(a)
      URL.revokeObjectURL(url)

      if (onDownload) onDownload()
    }
  }

  return (
    <div ref={reportRef}>
      <Card className={cn("w-full max-w-4xl mx-auto mt-6 border-2 rounded-xl bg-secondary")}>
        <CardHeader className="pb-4">
          <div className="flex items-center justify-between">
            <CardTitle className="flex items-center gap-2 text-xl">
              <FileText className="w-6 h-6" />
              Medical Consultation Report
            </CardTitle>
            <Button
              onClick={handleDownload}
              className="flex items-center gap-2"
              variant="outline"
            >
              <Download className="w-4 h-4" />
              {hasServerPdf ? 'Download Report (server)' : 'Download Report'}
            </Button>
          </div>
          <p className="text-sm text-muted-foreground flex items-center gap-2">
            <Calendar className="w-4 h-4" />
            Generated on {formatDate(report.generatedAt)}
          </p>
        </CardHeader>

        <CardContent className="space-y-6">
          {/* Patient Information */}
          <div className="bg-card rounded-lg p-4 border-2">
            <h3 className="font-semibold flex items-center gap-2 mb-3 text-lg">
              <User className="w-5 h-5" />
              Patient Information
            </h3>
            <div className="grid grid-cols-1 md:grid-cols-2 gap-4">
              <div>
                <label className="text-sm font-medium text-muted-foreground">Name</label>
                <p className="text-foreground">{report.patientInfo.name}</p>
              </div>
              <div>
                <label className="text-sm font-medium text-muted-foreground">Age</label>
                <p className="text-foreground">{report.patientInfo.age}</p>
              </div>
            </div>
          </div>

          {/* Chief Complaint */}
          <div className="bg-card rounded-lg p-4 border-2">
            <h3 className="font-semibold flex items-center gap-2 mb-3 text-lg">
              <Stethoscope className="w-5 h-5" />
              Chief Complaint
            </h3>
            <p className="text-foreground leading-relaxed">{report.chiefComplaint}</p>
          </div>

          {/* Medical History */}
          <div className="bg-card rounded-lg p-4 border-2">
            <h3 className="font-semibold flex items-center gap-2 mb-3 text-lg">
              <ClipboardList className="w-5 h-5" />
              Medical History
            </h3>
            <p className="text-foreground leading-relaxed">{report.medicalHistory}</p>
          </div>

          {/* Assessment */}
          <div className="bg-card rounded-lg p-4 border-2">
            <h3 className="font-semibold flex items-center gap-2 mb-3 text-lg">
              <FileText className="w-5 h-5" />
              Assessment/Diagnosis
            </h3>
            <p className="text-foreground leading-relaxed">{report.assessment}</p>
          </div>

          {/* Prescription */}
          <div className="bg-card rounded-lg p-4 border-2">
            <h3 className="font-semibold flex items-center gap-2 mb-3 text-lg">
              <Pill className="w-5 h-5" />
              Prescription/Recommendations
            </h3>
            <p className="text-foreground leading-relaxed whitespace-pre-line">{report.prescription}</p>
          </div>

          {/* Follow-up */}
          <div className="bg-card rounded-lg p-4 border-2">
            <h3 className="font-semibold flex items-center gap-2 mb-3 text-lg">
              <Calendar className="w-5 h-5" />
              Follow-up Instructions
            </h3>
            <p className="text-foreground leading-relaxed">{report.followUp}</p>
          </div>

          {/* Disclaimer */}
          <div className="bg-yellow-50 dark:bg-yellow-900/20 rounded-lg p-4 border-2 border-yellow-200 dark:border-yellow-800">
            <p className="text-sm text-yellow-800 dark:text-yellow-200">
              <strong>Important:</strong> This report was generated by an AI Medical Assistant.
              Please consult with a qualified healthcare professional for final diagnosis,
              treatment, and medical advice.
            </p>
          </div>
        </CardContent>
      </Card>
    </div>
  )
}

export default MedicalReport
